


// Generated by https://quicktype.io

export interface TicketsInputs {
    vendedor_id: number;
    jugadas:     Jugada[];
}

export interface Jugada {
    combinacion_id: number;
    monto:          number;
    loteria_id:     number;
    numeros:        Numero[];
}

export interface Numero {
    numero: number;
}
