


// Generated by https://quicktype.io

export interface TicketsInputs {
    vendedor_id: number;
    jugadas:     Jugada[];
}

export interface Jugada {
    id?:             string
    combinacion_id: number;
    monto:          number;
    loteria_id:     number;
    numeros:        Numero[];
}

export interface Numeros {
    numero: number
}

export interface Numero {
    numero: number;
}




// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface Test {
    vendedor_id: number;
    jugadas:     Jugada[];
}

export interface Jugada {
    combinacion_id: number;
    monto:          number;
    loteria_id:     number;
    numeros:        Numero[];
}

export interface Numero {
    numero: number;
}

