// Generated by https://quicktype.io

export interface Sucursales {
    id:         number;
    nombre:     string;
    direccion:  string;
    tipo:       string;
    created_at: string;
    updated_at: string;
}
