// Generated by https://quicktype.io

export interface LoginSuperadmin {
    status:       number;
    msg:          string;
    access_token: string;
    user:         User;
}

export interface User {
    id:                  number;
    name:                string;
    email:               string;
    email_verified_at:   null;
    created_at:          string;
    updated_at:          string;
    identification_card: string;
    cellphone:           string;
    phone:               null;
    address:             string;
    role_id:             number;
    sucursal_id:         null;
}


export interface Inputs{
    email: string,
    password: string
}

export interface Status{
    status: 'autenticated' | 'not-autenticated' | 'loading'
}